# Generated by Django 5.1.5 on 2025-03-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_limite', models.DateField()),
                ('statut', models.CharField(choices=[('A faire', 'À faire'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='A faire', max_length=20)),
            ],
        ),
    ]
