# Generated by Django 5.1.5 on 2025-03-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0006_projet_date_limite_projet_statut'),
        ('taches', '0003_tache_date_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tache',
            old_name='titre',
            new_name='nom',
        ),
        migrations.AlterField(
            model_name='tache',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='projets.projet'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('À faire', 'À faire'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='À faire', max_length=20),
        ),
    ]
