# Generated by Django 5.1.5 on 2025-03-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('PROFESSEUR', 'Professeur')], default='ETUDIANT', max_length=20),
        ),
    ]
