# Generated by Django 5.1.5 on 2025-03-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
