# Generated by Django 5.1.5 on 2025-03-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='chef_projet',
        ),
    ]
