# Generated by Django 5.1.5 on 2025-03-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0005_alter_projet_description_alter_projet_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='date_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('À faire', 'À faire'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='À faire', max_length=20),
        ),
    ]
